repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.8
      exclude: ^(migrations/|locale/)
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: ^(migrations/|locale/)
