[tool.poetry]
name = "graphene-django-cud"
version = "0.9.1"
description = ""
authors = ["Tormod Haugland <tormod.haugland@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
graphene-django = "^2.15"
graphene-file-upload = "^1.2"

[tool.poetry.dev-dependencies]
django = "^2.2"
pytest = "^5.2"
pytest-django = "^3.7"
factory_boy = "^2.12"
addict = "^2.2"
pytest-cov = "^2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
