[tool.poetry]
name = "graphene-django-cud"
version = "0.0.15"
description = ""
authors = ["Tormod Haugland <tormod.haugland@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
graphene-django = "^2.5"
graphene-file-upload = "^1.2"

[tool.poetry.dev-dependencies]
django = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
